"""add_context_files_table

Revision ID: 100ab91c7fc6
Revises: d2e3f4g5h6i7
Create Date: 2026-01-02 08:07:25.326672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100ab91c7fc6'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4g5h6i7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_context_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('gemini_uri', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_context_id'], ['ai_contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('ai_contexts', 'gemini_file_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_contexts', sa.Column('gemini_file_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('context_files')
    # ### end Alembic commands ###
