"""Initial migration: Multi-tenant schema

Revision ID: f62d190dfcf4
Revises: 
Create Date: 2025-11-20 03:24:05.310304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62d190dfcf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_table('fichas_cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('brand_archetype', sa.String(), nullable=True),
    sa.Column('tone_of_voice', sa.String(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('social_media_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('total_posts_analyzed', sa.Integer(), nullable=True),
    sa.Column('total_comments_analyzed', sa.Integer(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('q1_emociones', sa.JSON(), nullable=True),
    sa.Column('q2_personalidad', sa.JSON(), nullable=True),
    sa.Column('q3_topicos', sa.JSON(), nullable=True),
    sa.Column('q4_marcos_narrativos', sa.JSON(), nullable=True),
    sa.Column('q5_influenciadores', sa.JSON(), nullable=True),
    sa.Column('q6_oportunidades', sa.JSON(), nullable=True),
    sa.Column('q7_sentimiento', sa.JSON(), nullable=True),
    sa.Column('q8_temporal', sa.JSON(), nullable=True),
    sa.Column('q9_recomendaciones', sa.JSON(), nullable=True),
    sa.Column('q10_resumen', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['fichas_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['fichas_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_posts_post_url'), 'social_media_posts', ['post_url'], unique=True)
    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_media_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_social_media_posts_post_url'), table_name='social_media_posts')
    op.drop_table('social_media_posts')
    op.drop_table('social_media_insights')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fichas_cliente')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
