
import asyncio
import os
import sys
import json
from uuid import UUID

# Add parent directory to path to import app modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.services.database import db

# Client ID for "Nike" (from previous context or I'll query it/create it)
# Using a fixed ID for consistency if possible, or I'll look up by email "nike@demo.com"
# For safety, I'll fetch the client first or create if not exists.

async def seed_full_data():
    print("🚀 Starting Full Interview Data Seeding...")

    # 1. Ensure Client Exists
    client_id = "9f15d808-d39e-477b-8258-2cc20bbd46e7" # The ID we used for Nike before
    
    # Check if client exists, if not, might need to create or pick another.
    # For this script I'll assume standard flow: try to get or warn.
    
    # Payload matching MultiStepForm.tsx structure exactly
    full_interview_data = {
        "businessName": "Nike",
        "history": "Fundada en 1964 por Bill Bowerman y Phil Knight. Empezamos vendiendo zapatillas japonesas en el maletero de un coche. Hoy somos líderes mundiales en equipamiento deportivo, impulsados por la innovación y el diseño.",
        "vision": "Traer inspiración e innovación a cada atleta del mundo. (Si tienes cuerpo, eres un atleta).",
        "differentiator": [
            "Innovación tecnológica constante (Air, React, Flyknit)",
            "Marketing emocional y storytelling poderoso",
            "Patrocinios con los mejores atletas de la historia"
        ],
        "productFile": None, # Files handled separately ideally
        
        # STEP 2: AUDIENCE
        "audience": {
            "ageRange": "15-35 años",
            "gender": "Todos",
            "location": "Global / Urbano",
            "occupation": "Estudiantes, Atletas, Creativos",
            "maritalStatus": "Indiferente",
            "interests": "Deporte, Moda Streetwear, Música, Cultura Pop, Tecnología",
            "values": "Superación, Autenticidad, estilo, Pertenencia",
            "painPoints": "Ropa deportiva aburrida, mala calidad, falta de identidad, precios altos sin justificación",
            "desires": "Sentirse parte de una comunidad, mejorar rendimiento, lucir bien",
            "lifestyle": "Activo, Digital, Social",
            "incomeLevel": "Medio-Alto",
            "priceSensitivity": "Paga por Valor", # Options: ['Busca Ofertas', 'Equilibrado', 'Paga por Valor', 'Sin restricciones']
            "spendingHabits": "Impulsivo en lanzamientos (SNKRS app)",
            "frequency": "Mensual",
            "loyalty": "Embajador de Marca",
            "decisionRole": "Decisor Final",
            "usage": "Diario/Intensivo",
            
            # Personas (usually generated by AI, but seeded here)
            "idealPersona": {
                "name": "Alex, el Sneakerhead Determinado",
                "occupation": "Diseñador Gráfico / Runner Amateur",
                "location": "Ciudad de México",
                "ageRange": "24-29",
                "gender": "Masculino",
                "painPoints": "No conseguir los drops exclusivos. Ropa técnica que no se ve bien en la calle.",
                "incomeLevel": "Medio-Alto",
                "loyalty": "Alta",
                "interests": "Running, Diseño, Hypebeast culture",
                "values": "Estética, Exclusividad, Rendimiento",
                "spendingHabits": "Ahorra para comprar ediciones limitadas",
                "ideal_reason": "Alto LTV, genera contenido orgánico en redes, influye en su círculo."
            },
            "antiPersona": {
                "name": "Sr. Tradicional Ahorrador",
                "occupation": "Contable",
                "location": "Suburbios",
                "ageRange": "50+",
                "gender": "Masculino",
                "painPoints": "Precios absurdos para 'solo zapatos'. Diseños demasiado llamativos.",
                "incomeLevel": "Medio",
                "loyalty": "Baja",
                "interests": "Jardinería, TV, Comodidad básica",
                "values": "Funcionalidad pura, Ahorro",
                "spendingHabits": "Compra solo en rebajas extremas cada 2 años",
                "avoid_reason": "Coste de adquisición alto para margen bajo. No valora la marca, solo el precio."
            }
        },

        # STEP 3: MARKET
        "market": {
            "priceRange": "Alto", # ['Bajo', 'Medio', 'Alto', 'Lujo']
            "promotions": "Descuentos selectivos en app para miembros. Rebajas de temporada fin de línea.",
            "channels": ["Tienda Online", "Tienda Física", "Redes Sociales", "Marketplace"], # Labels from component
            "bestSellers": ["Air Jordan 1", "Air Force 1", "Pegasus Running"],
            "worstSellers": ["Línea básica oculta", "Accesorios genéricos"],
            "competitors": ["Adidas", "Puma", "Under Armour", "Lululemon", "New Balance"]
        },

        # STEP 4: BRAND / SITUATION
        "brand": {
            "socialNetworks": [
                {"platform": "Instagram", "link": "@nike", "frequency": "Diaria"},
                {"platform": "TikTok", "link": "@nike", "frequency": "3-4/Semana"},
                {"platform": "YouTube", "link": "Nike", "frequency": "Semanal"}
            ],
            "socialManager": "Equipo Interno",
            "adsExperience": "Inversión masiva en Brand Awareness (TV, Digital). Retargeting dinámico en web.",
            "bestContent": ["Campañas con atletas estrella", "Historias de superación", "Lanzamientos de producto (Drops)"],
            "badExperiences": "Controversias laborales en los 90 (ya superadas). Alguna campaña política polarizante."
        },

        # STEP 5: GOALS
        "goals": {
            "salesGoals": ["Aumentar ventas Direct-to-Consumer (DTC) un 15%", "Crecer en mercado femenino"],
            "brandGoals": ["Liderar sostenibilidad (Move to Zero)", "Expandir presencia en Metaverso"],
            "growthStrategy": ["Innovación Digital", "Personalización masiva"],
            "positioning": ["Innovador", "Inspirador", "Premium pero accesible", "Socialmente responsable"]
        }
    }

    try:
        # Load env vars manually to ensure we have Service Key
        from dotenv import load_dotenv
        load_dotenv()
        
        sb_url = os.getenv("SUPABASE_URL")
        sb_key = os.getenv("SUPABASE_SERVICE_KEY")
        
        if not sb_url or not sb_key:
            print("❌ Missing Service Key in .env")
            return

        from supabase import create_client
        admin_client = create_client(sb_url, sb_key)

        print(f"🔄 Updating/Creating interview for {client_id} using Admin Client...")
            
        payload = {
            "client_id": client_id,
            "data": full_interview_data,
            # updated_at optional depending on schema
        }

        # Upsert using admin client
        res = admin_client.table("client_interviews").upsert(payload, on_conflict="client_id").execute()
            
        print("✅ Data seeded successfully!")
        print("Business:", full_interview_data["businessName"])
        print("Audience Ideal:", full_interview_data["audience"]["idealPersona"]["name"])
        
    except Exception as e:
        print(f"❌ Error seeding data: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(seed_full_data())
